---
deployment:
  tasks:
    - export DEPLOYPATH=/home/navephnl/jasminelearning.com/
    - /bin/find $DEPLOYPATH -mindepth 1 ! -name 'zoho-config.php' -exec /bin/rm -rf {} +
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
